Q1

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.6'

Q2

In [5]:
data = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

In [6]:
!wget -q -O data.csv $data

In [7]:
df = pd.read_csv("data.csv")

In [14]:
df.shape

(10000, 11)

Q3

In [19]:
df['fuel_type'].nunique()

3

Q4

In [31]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5

In [33]:
df_asia = df[df['origin'] == 'Asia']

In [36]:
df_asia.shape

(2994, 11)

In [35]:
df_asia.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,2994.000000,2994.000000,2994.000000,2994.000000,2729.000000,2994.000000,2994.000000,2994.000000
mean,1999.436540,3.498664,2252.448230,5.998998,247.662514,4235.003340,18.897829,30.741015
std,14.251106,0.950582,184.008122,0.552308,21.321483,263.520367,1.315201,2.835474
min,1975.000000,2.000000,1590.000000,4.000000,174.000000,3320.000000,14.400000,21.300000
25%,1987.000000,3.000000,2130.000000,6.000000,234.000000,4060.000000,18.000000,28.700000
50%,1999.000000,4.000000,2260.000000,6.000000,248.000000,4230.000000,18.900000,30.700000
75%,2012.000000,4.000000,2370.000000,6.000000,262.000000,4410.000000,19.800000,32.500000
max,2024.000000,5.000000,3020.000000,8.000000,334.000000,5280.000000,23.800000,41.200000

Q6

In [37]:
df['horsepower'].median()

np.float64(254.0)

In [40]:
horsepower_mode = df['horsepower'].mode()[0]

In [41]:
df['horsepower'] = df['horsepower'].fillna(horsepower_mode)

In [42]:
df['horsepower'].median()

np.float64(252.0)

Q7

In [43]:
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [44]:
df_asia = df_asia[['vehicle_weight', 'model_year']]

In [45]:
X = df_asia.head(7).values

In [46]:
XTX = X.T @ X

In [47]:
XTX_inv = np.linalg.inv(XTX)

In [48]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [49]:
w = XTX_inv @ X.T @ y

In [50]:
w.sum()

np.float64(0.36919696904925486)